### ISSUE TITLE
only the last result is handled from multiple files

### ISSUE THREAD

**Issue by shaygalon** [jenkinsci/benchmark-plugin#12]
Sample job shell script of:
for i in {1..3} ; do
 mkdir -p run$i
 pushd run$i
 echo "{" > tracking.json
 echo "	'T' : $i," >> tracking.json
 echo "	'L' : $i " >> tracking.json
 echo "}" >> tracking.json
 popd
done

Schema:
{
    "description": "Performance tracking",
    "failure": { "value": true },
    "type": "object",
    "properties": {
                "T": {"type": "resultFull"},
                "L": {"type": "resultFull"}
        }
}

pick up run*/tracking.json

console output shows only 2 results, and benchmark table shows it is only the last one that was picked up:

Benchmark plugin - Collection of results started.
File pattern: run*/tracking.json
List of files detected:
   - test/run3/tracking.json
   - test/run3/tracking.json
   - test/run2/tracking.json
   - test/run2/tracking.json
   - test/run1/tracking.json
   - test/run1/tracking.json
Number of results:          2
Number of parameters:       0
Number of added thresholds: 0
Results contain numerals.
Strings are truncated.
Benchmark plugin - Collection of results completed.

**Comment by damercie** [comment]
Thank you for finding the bug.
Issue was fixed on version 1.0.4 after commit #13 .

Note: Careful with the script above, JSON standard supports only double quote.
